image: eclipse-temurin:17-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
  policy: pull

stages:
  - build
  - test
  - publish

build:
  stage: build
  script: ./gradlew build -x check
  cache:
    policy: pull-push
    paths:
      - .gradle

test:
  stage: test
  script: ./gradlew test
  artifacts:
    reports:
      junit: ./**/build/test-results/test/**/TEST-*.xml

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script: ./gradlew publish
